// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "3c6b67ca137a835190dfef99b4c970bb490c211d32cd6624e8cea1b09a861f48")
