// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/security/api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetEventParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventParams) Reset()         { *m = GetEventParams{} }
func (m *GetEventParams) String() string { return proto.CompactTextString(m) }
func (*GetEventParams) ProtoMessage()    {}
func (*GetEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{0}
}

func (m *GetEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventParams.Unmarshal(m, b)
}
func (m *GetEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventParams.Marshal(b, m, deterministic)
}
func (m *GetEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventParams.Merge(m, src)
}
func (m *GetEventParams) XXX_Size() int {
	return xxx_messageInfo_GetEventParams.Size(m)
}
func (m *GetEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventParams proto.InternalMessageInfo

type SecurityEventMessage struct {
	RuleID               string   `protobuf:"bytes,1,opt,name=RuleID,proto3" json:"RuleID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Service              string   `protobuf:"bytes,4,opt,name=Service,proto3" json:"Service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityEventMessage) Reset()         { *m = SecurityEventMessage{} }
func (m *SecurityEventMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityEventMessage) ProtoMessage()    {}
func (*SecurityEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{1}
}

func (m *SecurityEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityEventMessage.Unmarshal(m, b)
}
func (m *SecurityEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityEventMessage.Marshal(b, m, deterministic)
}
func (m *SecurityEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityEventMessage.Merge(m, src)
}
func (m *SecurityEventMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityEventMessage.Size(m)
}
func (m *SecurityEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityEventMessage proto.InternalMessageInfo

func (m *SecurityEventMessage) GetRuleID() string {
	if m != nil {
		return m.RuleID
	}
	return ""
}

func (m *SecurityEventMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SecurityEventMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SecurityEventMessage) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type DumpProcessCacheParams struct {
	WithArgs             bool     `protobuf:"varint,1,opt,name=WithArgs,proto3" json:"WithArgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpProcessCacheParams) Reset()         { *m = DumpProcessCacheParams{} }
func (m *DumpProcessCacheParams) String() string { return proto.CompactTextString(m) }
func (*DumpProcessCacheParams) ProtoMessage()    {}
func (*DumpProcessCacheParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{2}
}

func (m *DumpProcessCacheParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpProcessCacheParams.Unmarshal(m, b)
}
func (m *DumpProcessCacheParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpProcessCacheParams.Marshal(b, m, deterministic)
}
func (m *DumpProcessCacheParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpProcessCacheParams.Merge(m, src)
}
func (m *DumpProcessCacheParams) XXX_Size() int {
	return xxx_messageInfo_DumpProcessCacheParams.Size(m)
}
func (m *DumpProcessCacheParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpProcessCacheParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpProcessCacheParams proto.InternalMessageInfo

func (m *DumpProcessCacheParams) GetWithArgs() bool {
	if m != nil {
		return m.WithArgs
	}
	return false
}

type SecurityDumpProcessCacheMessage struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityDumpProcessCacheMessage) Reset()         { *m = SecurityDumpProcessCacheMessage{} }
func (m *SecurityDumpProcessCacheMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityDumpProcessCacheMessage) ProtoMessage()    {}
func (*SecurityDumpProcessCacheMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{3}
}

func (m *SecurityDumpProcessCacheMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Unmarshal(m, b)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Marshal(b, m, deterministic)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.Merge(m, src)
}
func (m *SecurityDumpProcessCacheMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityDumpProcessCacheMessage.Size(m)
}
func (m *SecurityDumpProcessCacheMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityDumpProcessCacheMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityDumpProcessCacheMessage proto.InternalMessageInfo

func (m *SecurityDumpProcessCacheMessage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type DumpNetworkNamespaceParams struct {
	SnapshotInterfaces   bool     `protobuf:"varint,1,opt,name=SnapshotInterfaces,proto3" json:"SnapshotInterfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceParams) Reset()         { *m = DumpNetworkNamespaceParams{} }
func (m *DumpNetworkNamespaceParams) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceParams) ProtoMessage()    {}
func (*DumpNetworkNamespaceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{4}
}

func (m *DumpNetworkNamespaceParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceParams.Merge(m, src)
}
func (m *DumpNetworkNamespaceParams) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceParams.Size(m)
}
func (m *DumpNetworkNamespaceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceParams proto.InternalMessageInfo

func (m *DumpNetworkNamespaceParams) GetSnapshotInterfaces() bool {
	if m != nil {
		return m.SnapshotInterfaces
	}
	return false
}

type DumpNetworkNamespaceMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	DumpFilename         string   `protobuf:"bytes,2,opt,name=DumpFilename,proto3" json:"DumpFilename,omitempty"`
	GraphFilename        string   `protobuf:"bytes,3,opt,name=GraphFilename,proto3" json:"GraphFilename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpNetworkNamespaceMessage) Reset()         { *m = DumpNetworkNamespaceMessage{} }
func (m *DumpNetworkNamespaceMessage) String() string { return proto.CompactTextString(m) }
func (*DumpNetworkNamespaceMessage) ProtoMessage()    {}
func (*DumpNetworkNamespaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{5}
}

func (m *DumpNetworkNamespaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Unmarshal(m, b)
}
func (m *DumpNetworkNamespaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Marshal(b, m, deterministic)
}
func (m *DumpNetworkNamespaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpNetworkNamespaceMessage.Merge(m, src)
}
func (m *DumpNetworkNamespaceMessage) XXX_Size() int {
	return xxx_messageInfo_DumpNetworkNamespaceMessage.Size(m)
}
func (m *DumpNetworkNamespaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpNetworkNamespaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DumpNetworkNamespaceMessage proto.InternalMessageInfo

func (m *DumpNetworkNamespaceMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetDumpFilename() string {
	if m != nil {
		return m.DumpFilename
	}
	return ""
}

func (m *DumpNetworkNamespaceMessage) GetGraphFilename() string {
	if m != nil {
		return m.GraphFilename
	}
	return ""
}

type GetConfigParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigParams) Reset()         { *m = GetConfigParams{} }
func (m *GetConfigParams) String() string { return proto.CompactTextString(m) }
func (*GetConfigParams) ProtoMessage()    {}
func (*GetConfigParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{6}
}

func (m *GetConfigParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigParams.Unmarshal(m, b)
}
func (m *GetConfigParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigParams.Marshal(b, m, deterministic)
}
func (m *GetConfigParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigParams.Merge(m, src)
}
func (m *GetConfigParams) XXX_Size() int {
	return xxx_messageInfo_GetConfigParams.Size(m)
}
func (m *GetConfigParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigParams proto.InternalMessageInfo

type SecurityConfigMessage struct {
	RuntimeEnabled       bool     `protobuf:"varint,1,opt,name=RuntimeEnabled,proto3" json:"RuntimeEnabled,omitempty"`
	FIMEnabled           bool     `protobuf:"varint,2,opt,name=FIMEnabled,proto3" json:"FIMEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityConfigMessage) Reset()         { *m = SecurityConfigMessage{} }
func (m *SecurityConfigMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityConfigMessage) ProtoMessage()    {}
func (*SecurityConfigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{7}
}

func (m *SecurityConfigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityConfigMessage.Unmarshal(m, b)
}
func (m *SecurityConfigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityConfigMessage.Marshal(b, m, deterministic)
}
func (m *SecurityConfigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityConfigMessage.Merge(m, src)
}
func (m *SecurityConfigMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityConfigMessage.Size(m)
}
func (m *SecurityConfigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityConfigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityConfigMessage proto.InternalMessageInfo

func (m *SecurityConfigMessage) GetRuntimeEnabled() bool {
	if m != nil {
		return m.RuntimeEnabled
	}
	return false
}

func (m *SecurityConfigMessage) GetFIMEnabled() bool {
	if m != nil {
		return m.FIMEnabled
	}
	return false
}

type RunSelfTestParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunSelfTestParams) Reset()         { *m = RunSelfTestParams{} }
func (m *RunSelfTestParams) String() string { return proto.CompactTextString(m) }
func (*RunSelfTestParams) ProtoMessage()    {}
func (*RunSelfTestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{8}
}

func (m *RunSelfTestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunSelfTestParams.Unmarshal(m, b)
}
func (m *RunSelfTestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunSelfTestParams.Marshal(b, m, deterministic)
}
func (m *RunSelfTestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunSelfTestParams.Merge(m, src)
}
func (m *RunSelfTestParams) XXX_Size() int {
	return xxx_messageInfo_RunSelfTestParams.Size(m)
}
func (m *RunSelfTestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunSelfTestParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunSelfTestParams proto.InternalMessageInfo

type ReloadPoliciesParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesParams) Reset()         { *m = ReloadPoliciesParams{} }
func (m *ReloadPoliciesParams) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesParams) ProtoMessage()    {}
func (*ReloadPoliciesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{9}
}

func (m *ReloadPoliciesParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesParams.Unmarshal(m, b)
}
func (m *ReloadPoliciesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesParams.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesParams.Merge(m, src)
}
func (m *ReloadPoliciesParams) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesParams.Size(m)
}
func (m *ReloadPoliciesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesParams proto.InternalMessageInfo

type ReloadPoliciesResultMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadPoliciesResultMessage) Reset()         { *m = ReloadPoliciesResultMessage{} }
func (m *ReloadPoliciesResultMessage) String() string { return proto.CompactTextString(m) }
func (*ReloadPoliciesResultMessage) ProtoMessage()    {}
func (*ReloadPoliciesResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{10}
}

func (m *ReloadPoliciesResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Unmarshal(m, b)
}
func (m *ReloadPoliciesResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Marshal(b, m, deterministic)
}
func (m *ReloadPoliciesResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadPoliciesResultMessage.Merge(m, src)
}
func (m *ReloadPoliciesResultMessage) XXX_Size() int {
	return xxx_messageInfo_ReloadPoliciesResultMessage.Size(m)
}
func (m *ReloadPoliciesResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadPoliciesResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadPoliciesResultMessage proto.InternalMessageInfo

type SecuritySelfTestResultMessage struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecuritySelfTestResultMessage) Reset()         { *m = SecuritySelfTestResultMessage{} }
func (m *SecuritySelfTestResultMessage) String() string { return proto.CompactTextString(m) }
func (*SecuritySelfTestResultMessage) ProtoMessage()    {}
func (*SecuritySelfTestResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{11}
}

func (m *SecuritySelfTestResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Unmarshal(m, b)
}
func (m *SecuritySelfTestResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Marshal(b, m, deterministic)
}
func (m *SecuritySelfTestResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecuritySelfTestResultMessage.Merge(m, src)
}
func (m *SecuritySelfTestResultMessage) XXX_Size() int {
	return xxx_messageInfo_SecuritySelfTestResultMessage.Size(m)
}
func (m *SecuritySelfTestResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecuritySelfTestResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecuritySelfTestResultMessage proto.InternalMessageInfo

func (m *SecuritySelfTestResultMessage) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SecuritySelfTestResultMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DumpActivityParams struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Comm                 string   `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	Timeout              int32    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	WithGraph            bool     `protobuf:"varint,4,opt,name=with_graph,json=withGraph,proto3" json:"with_graph,omitempty"`
	DifferentiateArgs    bool     `protobuf:"varint,5,opt,name=differentiate_args,json=differentiateArgs,proto3" json:"differentiate_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpActivityParams) Reset()         { *m = DumpActivityParams{} }
func (m *DumpActivityParams) String() string { return proto.CompactTextString(m) }
func (*DumpActivityParams) ProtoMessage()    {}
func (*DumpActivityParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{12}
}

func (m *DumpActivityParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpActivityParams.Unmarshal(m, b)
}
func (m *DumpActivityParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpActivityParams.Marshal(b, m, deterministic)
}
func (m *DumpActivityParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpActivityParams.Merge(m, src)
}
func (m *DumpActivityParams) XXX_Size() int {
	return xxx_messageInfo_DumpActivityParams.Size(m)
}
func (m *DumpActivityParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpActivityParams.DiscardUnknown(m)
}

var xxx_messageInfo_DumpActivityParams proto.InternalMessageInfo

func (m *DumpActivityParams) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *DumpActivityParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

func (m *DumpActivityParams) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *DumpActivityParams) GetWithGraph() bool {
	if m != nil {
		return m.WithGraph
	}
	return false
}

func (m *DumpActivityParams) GetDifferentiateArgs() bool {
	if m != nil {
		return m.DifferentiateArgs
	}
	return false
}

type SecurityActivityDumpMessage struct {
	OutputFilename       string   `protobuf:"bytes,1,opt,name=OutputFilename,proto3" json:"OutputFilename,omitempty"`
	GraphFilename        string   `protobuf:"bytes,2,opt,name=GraphFilename,proto3" json:"GraphFilename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpMessage) Reset()         { *m = SecurityActivityDumpMessage{} }
func (m *SecurityActivityDumpMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpMessage) ProtoMessage()    {}
func (*SecurityActivityDumpMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{13}
}

func (m *SecurityActivityDumpMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpMessage.Merge(m, src)
}
func (m *SecurityActivityDumpMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpMessage.Size(m)
}
func (m *SecurityActivityDumpMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpMessage) GetOutputFilename() string {
	if m != nil {
		return m.OutputFilename
	}
	return ""
}

func (m *SecurityActivityDumpMessage) GetGraphFilename() string {
	if m != nil {
		return m.GraphFilename
	}
	return ""
}

type ListActivityDumpsParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivityDumpsParams) Reset()         { *m = ListActivityDumpsParams{} }
func (m *ListActivityDumpsParams) String() string { return proto.CompactTextString(m) }
func (*ListActivityDumpsParams) ProtoMessage()    {}
func (*ListActivityDumpsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{14}
}

func (m *ListActivityDumpsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivityDumpsParams.Unmarshal(m, b)
}
func (m *ListActivityDumpsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivityDumpsParams.Marshal(b, m, deterministic)
}
func (m *ListActivityDumpsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivityDumpsParams.Merge(m, src)
}
func (m *ListActivityDumpsParams) XXX_Size() int {
	return xxx_messageInfo_ListActivityDumpsParams.Size(m)
}
func (m *ListActivityDumpsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivityDumpsParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivityDumpsParams proto.InternalMessageInfo

type SecurityActivityDumpListMessage struct {
	DumpTags             []string `protobuf:"bytes,1,rep,name=DumpTags,proto3" json:"DumpTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpListMessage) Reset()         { *m = SecurityActivityDumpListMessage{} }
func (m *SecurityActivityDumpListMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpListMessage) ProtoMessage()    {}
func (*SecurityActivityDumpListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{15}
}

func (m *SecurityActivityDumpListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpListMessage.Merge(m, src)
}
func (m *SecurityActivityDumpListMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpListMessage.Size(m)
}
func (m *SecurityActivityDumpListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpListMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpListMessage) GetDumpTags() []string {
	if m != nil {
		return m.DumpTags
	}
	return nil
}

type StopActivityDumpParams struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Comm                 string   `protobuf:"bytes,2,opt,name=Comm,proto3" json:"Comm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopActivityDumpParams) Reset()         { *m = StopActivityDumpParams{} }
func (m *StopActivityDumpParams) String() string { return proto.CompactTextString(m) }
func (*StopActivityDumpParams) ProtoMessage()    {}
func (*StopActivityDumpParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{16}
}

func (m *StopActivityDumpParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopActivityDumpParams.Unmarshal(m, b)
}
func (m *StopActivityDumpParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopActivityDumpParams.Marshal(b, m, deterministic)
}
func (m *StopActivityDumpParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopActivityDumpParams.Merge(m, src)
}
func (m *StopActivityDumpParams) XXX_Size() int {
	return xxx_messageInfo_StopActivityDumpParams.Size(m)
}
func (m *StopActivityDumpParams) XXX_DiscardUnknown() {
	xxx_messageInfo_StopActivityDumpParams.DiscardUnknown(m)
}

var xxx_messageInfo_StopActivityDumpParams proto.InternalMessageInfo

func (m *StopActivityDumpParams) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StopActivityDumpParams) GetComm() string {
	if m != nil {
		return m.Comm
	}
	return ""
}

type SecurityActivityDumpStoppedMessage struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityActivityDumpStoppedMessage) Reset()         { *m = SecurityActivityDumpStoppedMessage{} }
func (m *SecurityActivityDumpStoppedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityActivityDumpStoppedMessage) ProtoMessage()    {}
func (*SecurityActivityDumpStoppedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{17}
}

func (m *SecurityActivityDumpStoppedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Unmarshal(m, b)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.Merge(m, src)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityActivityDumpStoppedMessage.Size(m)
}
func (m *SecurityActivityDumpStoppedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityActivityDumpStoppedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityActivityDumpStoppedMessage proto.InternalMessageInfo

func (m *SecurityActivityDumpStoppedMessage) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateProfileParams struct {
	ActivityDumpFile     string   `protobuf:"bytes,1,opt,name=ActivityDumpFile,proto3" json:"ActivityDumpFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateProfileParams) Reset()         { *m = GenerateProfileParams{} }
func (m *GenerateProfileParams) String() string { return proto.CompactTextString(m) }
func (*GenerateProfileParams) ProtoMessage()    {}
func (*GenerateProfileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{18}
}

func (m *GenerateProfileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateProfileParams.Unmarshal(m, b)
}
func (m *GenerateProfileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateProfileParams.Marshal(b, m, deterministic)
}
func (m *GenerateProfileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateProfileParams.Merge(m, src)
}
func (m *GenerateProfileParams) XXX_Size() int {
	return xxx_messageInfo_GenerateProfileParams.Size(m)
}
func (m *GenerateProfileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateProfileParams.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateProfileParams proto.InternalMessageInfo

func (m *GenerateProfileParams) GetActivityDumpFile() string {
	if m != nil {
		return m.ActivityDumpFile
	}
	return ""
}

type SecurityProfileGeneratedMessage struct {
	ProfilePath          string   `protobuf:"bytes,1,opt,name=ProfilePath,proto3" json:"ProfilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecurityProfileGeneratedMessage) Reset()         { *m = SecurityProfileGeneratedMessage{} }
func (m *SecurityProfileGeneratedMessage) String() string { return proto.CompactTextString(m) }
func (*SecurityProfileGeneratedMessage) ProtoMessage()    {}
func (*SecurityProfileGeneratedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce049ba84fb5261a, []int{19}
}

func (m *SecurityProfileGeneratedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Unmarshal(m, b)
}
func (m *SecurityProfileGeneratedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Marshal(b, m, deterministic)
}
func (m *SecurityProfileGeneratedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecurityProfileGeneratedMessage.Merge(m, src)
}
func (m *SecurityProfileGeneratedMessage) XXX_Size() int {
	return xxx_messageInfo_SecurityProfileGeneratedMessage.Size(m)
}
func (m *SecurityProfileGeneratedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecurityProfileGeneratedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecurityProfileGeneratedMessage proto.InternalMessageInfo

func (m *SecurityProfileGeneratedMessage) GetProfilePath() string {
	if m != nil {
		return m.ProfilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*GetEventParams)(nil), "api.GetEventParams")
	proto.RegisterType((*SecurityEventMessage)(nil), "api.SecurityEventMessage")
	proto.RegisterType((*DumpProcessCacheParams)(nil), "api.DumpProcessCacheParams")
	proto.RegisterType((*SecurityDumpProcessCacheMessage)(nil), "api.SecurityDumpProcessCacheMessage")
	proto.RegisterType((*DumpNetworkNamespaceParams)(nil), "api.DumpNetworkNamespaceParams")
	proto.RegisterType((*DumpNetworkNamespaceMessage)(nil), "api.DumpNetworkNamespaceMessage")
	proto.RegisterType((*GetConfigParams)(nil), "api.GetConfigParams")
	proto.RegisterType((*SecurityConfigMessage)(nil), "api.SecurityConfigMessage")
	proto.RegisterType((*RunSelfTestParams)(nil), "api.RunSelfTestParams")
	proto.RegisterType((*ReloadPoliciesParams)(nil), "api.ReloadPoliciesParams")
	proto.RegisterType((*ReloadPoliciesResultMessage)(nil), "api.ReloadPoliciesResultMessage")
	proto.RegisterType((*SecuritySelfTestResultMessage)(nil), "api.SecuritySelfTestResultMessage")
	proto.RegisterType((*DumpActivityParams)(nil), "api.DumpActivityParams")
	proto.RegisterType((*SecurityActivityDumpMessage)(nil), "api.SecurityActivityDumpMessage")
	proto.RegisterType((*ListActivityDumpsParams)(nil), "api.ListActivityDumpsParams")
	proto.RegisterType((*SecurityActivityDumpListMessage)(nil), "api.SecurityActivityDumpListMessage")
	proto.RegisterType((*StopActivityDumpParams)(nil), "api.StopActivityDumpParams")
	proto.RegisterType((*SecurityActivityDumpStoppedMessage)(nil), "api.SecurityActivityDumpStoppedMessage")
	proto.RegisterType((*GenerateProfileParams)(nil), "api.GenerateProfileParams")
	proto.RegisterType((*SecurityProfileGeneratedMessage)(nil), "api.SecurityProfileGeneratedMessage")
}

func init() { proto.RegisterFile("pkg/security/api/api.proto", fileDescriptor_ce049ba84fb5261a) }

var fileDescriptor_ce049ba84fb5261a = []byte{
	// 852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0xa5, 0xe4, 0x8f, 0xda, 0x93, 0x54, 0x95, 0x27, 0x8a, 0xa2, 0xd0, 0x75, 0x23, 0x2c, 0x82,
	0xd6, 0x28, 0x50, 0xa7, 0x68, 0x7b, 0x2a, 0x50, 0xb4, 0xa9, 0xac, 0x18, 0x46, 0xe3, 0x58, 0xa0,
	0x52, 0x04, 0x4d, 0x0f, 0xc6, 0x86, 0x1a, 0x49, 0x0b, 0x51, 0x24, 0x41, 0x2e, 0x1d, 0xf8, 0xd0,
	0x7f, 0xd3, 0x3f, 0xd2, 0x7f, 0x56, 0xec, 0x72, 0x97, 0x21, 0x29, 0xca, 0x07, 0x01, 0x9c, 0xe1,
	0xcc, 0xe3, 0xd3, 0xcc, 0xdb, 0x47, 0x82, 0x1b, 0xaf, 0x16, 0x2f, 0x52, 0xf2, 0xb3, 0x44, 0xc8,
	0xbb, 0x17, 0x3c, 0x16, 0xea, 0x77, 0x16, 0x27, 0x91, 0x8c, 0x70, 0x87, 0xc7, 0x82, 0x75, 0xa1,
	0x73, 0x41, 0x72, 0x7c, 0x4b, 0xa1, 0x9c, 0xf0, 0x84, 0xaf, 0x53, 0x16, 0x43, 0x6f, 0x6a, 0x1a,
	0x74, 0xfa, 0x8a, 0xd2, 0x94, 0x2f, 0x08, 0xfb, 0xb0, 0xef, 0x65, 0x01, 0x5d, 0x9e, 0x0f, 0x5a,
	0xc3, 0xd6, 0xe9, 0xa1, 0x67, 0x22, 0x44, 0xd8, 0x3d, 0xe7, 0x92, 0x0f, 0xda, 0xc3, 0xd6, 0xe9,
	0x43, 0x4f, 0x5f, 0xab, 0xdc, 0x5b, 0xbe, 0x48, 0x07, 0x3b, 0xc3, 0x9d, 0xd3, 0x43, 0x4f, 0x5f,
	0xe3, 0x00, 0x3e, 0x9b, 0x52, 0x72, 0x2b, 0x7c, 0x1a, 0xec, 0x6a, 0x00, 0x1b, 0xb2, 0x9f, 0xa0,
	0x7f, 0x9e, 0xad, 0xe3, 0x49, 0x12, 0xf9, 0x94, 0xa6, 0x23, 0xee, 0x2f, 0x29, 0xe7, 0x82, 0x2e,
	0x1c, 0xbc, 0x13, 0x72, 0xf9, 0x32, 0x59, 0xa4, 0xfa, 0xa9, 0x07, 0x5e, 0x11, 0xb3, 0x5f, 0xe0,
	0x99, 0xe5, 0x59, 0xef, 0xb6, 0x94, 0x5d, 0x38, 0x78, 0x25, 0x02, 0x0a, 0xf9, 0x9a, 0x0c, 0xe9,
	0x22, 0x66, 0xaf, 0xc1, 0x55, 0x6d, 0x6f, 0x48, 0x7e, 0x8c, 0x92, 0xd5, 0x1b, 0xbe, 0xa6, 0x34,
	0xe6, 0xbe, 0x7d, 0xf0, 0x19, 0xe0, 0x34, 0xe4, 0x71, 0xba, 0x8c, 0xe4, 0x65, 0x28, 0x29, 0x99,
	0x73, 0x9f, 0x2c, 0x85, 0x86, 0x3b, 0xec, 0x1f, 0x38, 0x6e, 0x42, 0xb3, 0x44, 0x7a, 0xb0, 0x47,
	0x49, 0x12, 0x25, 0x86, 0x45, 0x1e, 0x20, 0x83, 0x87, 0xaa, 0xa9, 0xa0, 0xd8, 0xd6, 0x37, 0x2b,
	0x39, 0x7c, 0x0e, 0x9f, 0x5f, 0x24, 0x3c, 0x5e, 0x16, 0x45, 0x3b, 0xba, 0xa8, 0x9a, 0x64, 0x47,
	0xf0, 0xc5, 0x05, 0xc9, 0x51, 0x14, 0xce, 0xc5, 0xc2, 0xac, 0xf1, 0x06, 0x1e, 0xdb, 0xf1, 0xe4,
	0x79, 0xcb, 0xe5, 0x6b, 0xe8, 0x78, 0x59, 0x28, 0xc5, 0x9a, 0xc6, 0x21, 0xff, 0x10, 0xd0, 0xcc,
	0xfc, 0xad, 0x5a, 0x16, 0xbf, 0x02, 0x78, 0x75, 0x79, 0x65, 0x6b, 0xda, 0xba, 0xa6, 0x94, 0x61,
	0x8f, 0xe0, 0xc8, 0xcb, 0xc2, 0x29, 0x05, 0xf3, 0xb7, 0x94, 0x5a, 0xf1, 0xf4, 0xa1, 0xe7, 0x51,
	0x10, 0xf1, 0xd9, 0x24, 0x0a, 0x84, 0x2f, 0x28, 0x35, 0xf9, 0x13, 0x38, 0xae, 0xe6, 0x3d, 0x4a,
	0xb3, 0xc0, 0x6a, 0x8b, 0x8d, 0xe1, 0xc4, 0x92, 0xb5, 0x80, 0x95, 0x02, 0xec, 0x40, 0xfb, 0x7a,
	0x65, 0x88, 0xb6, 0xaf, 0x57, 0x6a, 0xa0, 0x63, 0x3d, 0xd0, 0x7c, 0x66, 0x79, 0xc0, 0xfe, 0x6d,
	0x01, 0xaa, 0xe9, 0xbd, 0xf4, 0xa5, 0xb8, 0x15, 0xf2, 0xce, 0x2c, 0xd3, 0xaa, 0xb1, 0x55, 0x52,
	0x23, 0xc2, 0xae, 0x1f, 0xad, 0xd7, 0xa6, 0x5f, 0x5f, 0x2b, 0x85, 0xaa, 0x01, 0x44, 0x99, 0xd4,
	0x53, 0xde, 0xf3, 0x6c, 0x88, 0x27, 0x00, 0x1f, 0x85, 0x5c, 0xde, 0x2c, 0xd4, 0xd4, 0xb5, 0x7c,
	0x0f, 0xbc, 0x43, 0x95, 0xd1, 0x6b, 0xc0, 0xef, 0x00, 0x67, 0x62, 0x3e, 0xa7, 0x84, 0x42, 0x29,
	0xb8, 0xa4, 0x1b, 0xae, 0x04, 0xbb, 0xa7, 0xcb, 0x8e, 0x2a, 0x77, 0xb4, 0x72, 0x57, 0x70, 0x6c,
	0xff, 0xad, 0x65, 0xaa, 0x58, 0x97, 0x16, 0x74, 0x9d, 0xc9, 0x38, 0x93, 0x35, 0xed, 0xd6, 0xb2,
	0x9b, 0xd2, 0x68, 0x37, 0x49, 0xe3, 0x29, 0x3c, 0x79, 0x2d, 0x52, 0x59, 0x7e, 0x90, 0x5d, 0x4a,
	0xe9, 0x04, 0x95, 0x6f, 0xab, 0xf2, 0xd2, 0x09, 0x52, 0xa9, 0xd2, 0xf8, 0x8a, 0x98, 0xfd, 0x06,
	0xfd, 0xa9, 0x8c, 0xe2, 0x72, 0xeb, 0xfd, 0x03, 0x1f, 0x95, 0x06, 0xae, 0xae, 0xd9, 0xcf, 0xc0,
	0x9a, 0x08, 0x28, 0xd4, 0x98, 0x66, 0xa5, 0xc3, 0x33, 0x2e, 0x1f, 0x9e, 0x7c, 0xd7, 0x23, 0x78,
	0x7c, 0x41, 0x21, 0x25, 0x5c, 0xd2, 0x24, 0x89, 0xe6, 0x22, 0xb0, 0x47, 0xf7, 0x5b, 0xe8, 0x96,
	0xc1, 0xd4, 0x20, 0x4c, 0xe7, 0x46, 0x9e, 0x8d, 0x3e, 0x4d, 0xc0, 0x80, 0x58, 0xcc, 0xe2, 0xe9,
	0x43, 0x78, 0x50, 0xe0, 0xcb, 0xa5, 0x41, 0x2a, 0xa7, 0x7e, 0xf8, 0x6f, 0x1f, 0x3a, 0x16, 0xe5,
	0x2a, 0x9a, 0x65, 0x01, 0xe1, 0xaf, 0x70, 0x68, 0x5d, 0x35, 0xc5, 0x47, 0x67, 0xca, 0x73, 0xab,
	0x2e, 0xeb, 0x3e, 0xd5, 0xc9, 0x26, 0xa3, 0x65, 0xce, 0xf7, 0x2d, 0x7c, 0x07, 0xdd, 0xba, 0xa9,
	0xe1, 0xb1, 0x6e, 0x69, 0x76, 0x4a, 0xf7, 0x79, 0x05, 0x6f, 0x8b, 0x21, 0x32, 0x07, 0xff, 0xc8,
	0x3d, 0xc7, 0x4e, 0x02, 0x9f, 0x14, 0xa0, 0xd5, 0x43, 0xe3, 0x0e, 0x2b, 0x80, 0x0d, 0x3a, 0x65,
	0x0e, 0xfe, 0x05, 0x47, 0x1b, 0xda, 0xc2, 0x2f, 0x75, 0xe3, 0x16, 0xcd, 0xd5, 0x78, 0x6e, 0x91,
	0x1d, 0x73, 0xf0, 0x3d, 0x74, 0xeb, 0xe2, 0x32, 0x03, 0x68, 0xd6, 0x9c, 0xfb, 0xcd, 0x56, 0xe0,
	0xaa, 0x9c, 0x98, 0x83, 0x7f, 0x2a, 0xb7, 0xac, 0x48, 0x07, 0x5d, 0xb3, 0xa3, 0x06, 0x41, 0xd5,
	0x28, 0x6f, 0xd1, 0x09, 0x73, 0xcc, 0xd2, 0x73, 0xb3, 0xc5, 0x9e, 0x5d, 0x7a, 0xd9, 0x94, 0x5d,
	0xb7, 0x02, 0x55, 0xf1, 0x65, 0xbd, 0x9b, 0x07, 0x25, 0x47, 0xc5, 0xbe, 0x2e, 0xde, 0xf0, 0x58,
	0x97, 0x55, 0x40, 0x1a, 0xfd, 0x92, 0x39, 0x78, 0x0d, 0x9d, 0xaa, 0xe3, 0x62, 0x2e, 0xb9, 0x26,
	0x7b, 0x36, 0xcb, 0xbe, 0xcf, 0xa1, 0x1d, 0xfc, 0x1b, 0x7a, 0x4d, 0xaf, 0x38, 0x7c, 0x56, 0x28,
	0xa8, 0xf9, 0x5d, 0x6a, 0xc0, 0xef, 0x79, 0x3d, 0x32, 0xe7, 0x77, 0x7c, 0xdf, 0xad, 0x7f, 0xa9,
	0x7c, 0xd8, 0xd7, 0x9f, 0x29, 0x3f, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x00, 0x9a, 0x8c, 0x96,
	0xc4, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecurityModuleClient is the client API for SecurityModule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecurityModuleClient interface {
	GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error)
	DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error)
	DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error)
	GenerateProfile(ctx context.Context, in *GenerateProfileParams, opts ...grpc.CallOption) (*SecurityProfileGeneratedMessage, error)
	GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error)
	RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error)
}

type securityModuleClient struct {
	cc *grpc.ClientConn
}

func NewSecurityModuleClient(cc *grpc.ClientConn) SecurityModuleClient {
	return &securityModuleClient{cc}
}

func (c *securityModuleClient) GetEvents(ctx context.Context, in *GetEventParams, opts ...grpc.CallOption) (SecurityModule_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SecurityModule_serviceDesc.Streams[0], "/api.SecurityModule/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &securityModuleGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecurityModule_GetEventsClient interface {
	Recv() (*SecurityEventMessage, error)
	grpc.ClientStream
}

type securityModuleGetEventsClient struct {
	grpc.ClientStream
}

func (x *securityModuleGetEventsClient) Recv() (*SecurityEventMessage, error) {
	m := new(SecurityEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityModuleClient) DumpProcessCache(ctx context.Context, in *DumpProcessCacheParams, opts ...grpc.CallOption) (*SecurityDumpProcessCacheMessage, error) {
	out := new(SecurityDumpProcessCacheMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpProcessCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpActivity(ctx context.Context, in *DumpActivityParams, opts ...grpc.CallOption) (*SecurityActivityDumpMessage, error) {
	out := new(SecurityActivityDumpMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ListActivityDumps(ctx context.Context, in *ListActivityDumpsParams, opts ...grpc.CallOption) (*SecurityActivityDumpListMessage, error) {
	out := new(SecurityActivityDumpListMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ListActivityDumps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) StopActivityDump(ctx context.Context, in *StopActivityDumpParams, opts ...grpc.CallOption) (*SecurityActivityDumpStoppedMessage, error) {
	out := new(SecurityActivityDumpStoppedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/StopActivityDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GenerateProfile(ctx context.Context, in *GenerateProfileParams, opts ...grpc.CallOption) (*SecurityProfileGeneratedMessage, error) {
	out := new(SecurityProfileGeneratedMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GenerateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) GetConfig(ctx context.Context, in *GetConfigParams, opts ...grpc.CallOption) (*SecurityConfigMessage, error) {
	out := new(SecurityConfigMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) RunSelfTest(ctx context.Context, in *RunSelfTestParams, opts ...grpc.CallOption) (*SecuritySelfTestResultMessage, error) {
	out := new(SecuritySelfTestResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/RunSelfTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) ReloadPolicies(ctx context.Context, in *ReloadPoliciesParams, opts ...grpc.CallOption) (*ReloadPoliciesResultMessage, error) {
	out := new(ReloadPoliciesResultMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/ReloadPolicies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityModuleClient) DumpNetworkNamespace(ctx context.Context, in *DumpNetworkNamespaceParams, opts ...grpc.CallOption) (*DumpNetworkNamespaceMessage, error) {
	out := new(DumpNetworkNamespaceMessage)
	err := c.cc.Invoke(ctx, "/api.SecurityModule/DumpNetworkNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityModuleServer is the server API for SecurityModule service.
type SecurityModuleServer interface {
	GetEvents(*GetEventParams, SecurityModule_GetEventsServer) error
	DumpProcessCache(context.Context, *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error)
	DumpActivity(context.Context, *DumpActivityParams) (*SecurityActivityDumpMessage, error)
	ListActivityDumps(context.Context, *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error)
	StopActivityDump(context.Context, *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error)
	GenerateProfile(context.Context, *GenerateProfileParams) (*SecurityProfileGeneratedMessage, error)
	GetConfig(context.Context, *GetConfigParams) (*SecurityConfigMessage, error)
	RunSelfTest(context.Context, *RunSelfTestParams) (*SecuritySelfTestResultMessage, error)
	ReloadPolicies(context.Context, *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error)
	DumpNetworkNamespace(context.Context, *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error)
}

// UnimplementedSecurityModuleServer can be embedded to have forward compatible implementations.
type UnimplementedSecurityModuleServer struct {
}

func (*UnimplementedSecurityModuleServer) GetEvents(req *GetEventParams, srv SecurityModule_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpProcessCache(ctx context.Context, req *DumpProcessCacheParams) (*SecurityDumpProcessCacheMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpProcessCache not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpActivity(ctx context.Context, req *DumpActivityParams) (*SecurityActivityDumpMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpActivity not implemented")
}
func (*UnimplementedSecurityModuleServer) ListActivityDumps(ctx context.Context, req *ListActivityDumpsParams) (*SecurityActivityDumpListMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivityDumps not implemented")
}
func (*UnimplementedSecurityModuleServer) StopActivityDump(ctx context.Context, req *StopActivityDumpParams) (*SecurityActivityDumpStoppedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopActivityDump not implemented")
}
func (*UnimplementedSecurityModuleServer) GenerateProfile(ctx context.Context, req *GenerateProfileParams) (*SecurityProfileGeneratedMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateProfile not implemented")
}
func (*UnimplementedSecurityModuleServer) GetConfig(ctx context.Context, req *GetConfigParams) (*SecurityConfigMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedSecurityModuleServer) RunSelfTest(ctx context.Context, req *RunSelfTestParams) (*SecuritySelfTestResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSelfTest not implemented")
}
func (*UnimplementedSecurityModuleServer) ReloadPolicies(ctx context.Context, req *ReloadPoliciesParams) (*ReloadPoliciesResultMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadPolicies not implemented")
}
func (*UnimplementedSecurityModuleServer) DumpNetworkNamespace(ctx context.Context, req *DumpNetworkNamespaceParams) (*DumpNetworkNamespaceMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpNetworkNamespace not implemented")
}

func RegisterSecurityModuleServer(s *grpc.Server, srv SecurityModuleServer) {
	s.RegisterService(&_SecurityModule_serviceDesc, srv)
}

func _SecurityModule_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityModuleServer).GetEvents(m, &securityModuleGetEventsServer{stream})
}

type SecurityModule_GetEventsServer interface {
	Send(*SecurityEventMessage) error
	grpc.ServerStream
}

type securityModuleGetEventsServer struct {
	grpc.ServerStream
}

func (x *securityModuleGetEventsServer) Send(m *SecurityEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _SecurityModule_DumpProcessCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpProcessCacheParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpProcessCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpProcessCache(ctx, req.(*DumpProcessCacheParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpActivityParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpActivity(ctx, req.(*DumpActivityParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ListActivityDumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivityDumpsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ListActivityDumps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ListActivityDumps(ctx, req.(*ListActivityDumpsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_StopActivityDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopActivityDumpParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/StopActivityDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).StopActivityDump(ctx, req.(*StopActivityDumpParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GenerateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateProfileParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GenerateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GenerateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GenerateProfile(ctx, req.(*GenerateProfileParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).GetConfig(ctx, req.(*GetConfigParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_RunSelfTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSelfTestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/RunSelfTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).RunSelfTest(ctx, req.(*RunSelfTestParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_ReloadPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPoliciesParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/ReloadPolicies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).ReloadPolicies(ctx, req.(*ReloadPoliciesParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityModule_DumpNetworkNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpNetworkNamespaceParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SecurityModule/DumpNetworkNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityModuleServer).DumpNetworkNamespace(ctx, req.(*DumpNetworkNamespaceParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecurityModule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SecurityModule",
	HandlerType: (*SecurityModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DumpProcessCache",
			Handler:    _SecurityModule_DumpProcessCache_Handler,
		},
		{
			MethodName: "DumpActivity",
			Handler:    _SecurityModule_DumpActivity_Handler,
		},
		{
			MethodName: "ListActivityDumps",
			Handler:    _SecurityModule_ListActivityDumps_Handler,
		},
		{
			MethodName: "StopActivityDump",
			Handler:    _SecurityModule_StopActivityDump_Handler,
		},
		{
			MethodName: "GenerateProfile",
			Handler:    _SecurityModule_GenerateProfile_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SecurityModule_GetConfig_Handler,
		},
		{
			MethodName: "RunSelfTest",
			Handler:    _SecurityModule_RunSelfTest_Handler,
		},
		{
			MethodName: "ReloadPolicies",
			Handler:    _SecurityModule_ReloadPolicies_Handler,
		},
		{
			MethodName: "DumpNetworkNamespace",
			Handler:    _SecurityModule_DumpNetworkNamespace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _SecurityModule_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/security/api/api.proto",
}
